#pragma once
#define GROUP_NAME L"GRUPO_CONTROLE_TEMPERATURA"
#define TEMP_Z_PRE_AQUE L"TEMP_Z_PRE_AQUE"
#define TEMP_Z_AQUE L"TEMP_Z_AQUE"
#define TEMP_Z_ENCH L"TEMP_Z_ENCH"
#define FLOW_TOTAL_GAS L"FLOW_TOTAL_GAS"

#define SP_TEMP_Z_PRE_AQUE L"SP_TEMP_Z_PRE_AQUE"
#define SP_TEMP_Z_AQUE L"SP_TEMP_Z_AQUE"
#define SP_TEMP_Z_ENCH L"SP_TEMP_Z_ENCH"

#define TEMP_Z_PRE_AQUE_CLIENT 1
#define TEMP_Z_AQUE_CLIENT 2
#define TEMP_Z_ENCH_CLIENT 3
#define FLOW_TOTAL_GAS_CLIENT 4
#define SP_TEMP_Z_PRE_AQUE_CLIENT 5
#define SP_TEMP_Z_AQUE_CLIENT 6
#define SP_TEMP_Z_ENCH_CLIENT 7